version: "3.5"
services:
  nginx:
    container_name: nginx_container
    image: nginx
    ports:
      - "80:80"
    restart: unless-stopped
    volumes:
      - /home/daniel/compose-nginx/html:/usr/share/nginx/html
